services:
  cloudary-postgres:
    image: postgres:16
    container_name: cloudary_pg_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudary
    ports:
      - "5432:5432"
    volumes:
      - cloudary_vol_pg:/var/lib/postgresql/data
    networks:
      - cloudary-network
  cloudary-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cloudary_pgadmin_dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - cloudary_vol_pgadmin:/var/lib/pgadmin
    networks:
      - cloudary-network
  redis:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - cloudary_redis_data:/data
    networks:
      - cloudary-network
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/local/observability/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - cloudary-network
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        /run.sh
    ports:
      - "3000:3000"
    volumes:
      - ./infra/local/observability/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - cloudary-network

networks:
  cloudary-network:
    driver: bridge

volumes:
  cloudary_vol_pg:
  cloudary_vol_pgadmin:
  cloudary_redis_data: