-- ============================================================================
-- Baseline schema for cloudary
-- Flyway baseline migration
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SCHEMA
-- ----------------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS public;

-- ----------------------------------------------------------------------------
-- TABLES
-- ----------------------------------------------------------------------------

CREATE TABLE public.event_publication (
  id uuid NOT NULL,
  completion_attempts integer NOT NULL,
  completion_date timestamp(6) with time zone,
  event_type character varying(255),
  last_resubmission_date timestamp(6) with time zone,
  listener_id character varying(255),
  publication_date timestamp(6) with time zone,
  serialized_event character varying(255),
  status character varying(255),
  CONSTRAINT event_publication_pkey PRIMARY KEY (id),
  CONSTRAINT event_publication_status_check
      CHECK (status IN (
            'PUBLISHED',
            'PROCESSING',
            'COMPLETED',
            'FAILED',
            'RESUBMITTED'
          ))
);

CREATE TABLE public.refresh_tokens (
   jti uuid NOT NULL,
   expiry timestamp(6) without time zone,
   hashed_token character varying(255),
   CONSTRAINT refresh_tokens_pkey PRIMARY KEY (jti)
);

CREATE TABLE public.roles (
  role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  authority character varying(255)
);

CREATE TABLE public.uploaded_files (
   file_id uuid NOT NULL,
   content_type character varying(255),
   file_name character varying(255),
   owner_id uuid,
   s3_etag character varying(255),
   s3_key character varying(255),
   size bigint,
   uploaded_at timestamp(6) with time zone,
   CONSTRAINT uploaded_files_pkey PRIMARY KEY (file_id)
);

CREATE TABLE public.user_file_permission (
 permission_id uuid NOT NULL,
 file_id uuid,
 user_id uuid,
 CONSTRAINT user_file_permission_pkey PRIMARY KEY (permission_id)
);

CREATE TABLE public.users (
  user_id uuid NOT NULL,
  email character varying(255),
  enabled boolean,
  first_name character varying(255),
  last_name character varying(255),
  password character varying(255),
  username character varying(255),
  verification_code integer,
  verification_code_expiration timestamp(6) without time zone,
  CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE public.user_roles (
   user_id uuid NOT NULL,
   role_id bigint NOT NULL,
   CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
   CONSTRAINT fk_user_roles_user
       FOREIGN KEY (user_id)
           REFERENCES public.users(user_id),
   CONSTRAINT fk_user_roles_role
       FOREIGN KEY (role_id)
           REFERENCES public.roles(role_id)
);

-- ---------------------------------------------------
-- CREATE ROLES
-- ---------------------------------------------------

INSERT INTO public.roles (authority) VALUES
 ('USER'),
 ('ADMIN')
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------
-- ADD EXTRA FOREIGN KEYS
-- ---------------------------------------------------

ALTER TABLE public.uploaded_files
    ADD CONSTRAINT fk_uploaded_files_owner
        FOREIGN KEY (owner_id)
            REFERENCES public.users(user_id);

ALTER TABLE public.user_file_permission
    ADD CONSTRAINT fk_user_file_permission_users
        FOREIGN KEY (user_id)
            REFERENCES public.users(user_id);

ALTER TABLE public.user_file_permission
    ADD CONSTRAINT fk_user_file_permission_file
        FOREIGN KEY (file_id) REFERENCES public.uploaded_files(file_id);